apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-reg
spec:
  selector:
    matchLabels:
      app: py-app
  replicas: 1
  template:
    metadata:
      labels:
        app: py-app
    spec:
     containers:
      - name: private-reg-container
        image: registry2021.jfrog.io/default-docker-virtual/flaskapp:v1.1
     imagePullSecrets:
       - name: regcred
