apiVersion: v1
kind: Service
metadata:
  labels:
    app: py-app
  name: py-app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
